#!/bin/bash

# exit on error
set -e

hosts=( roundcube12.xs4all.net )

while getopts "st" opt; do
  case $opt in
    t) TEST=1 ;;
    *) echo "Usage: $0 -t  (-t to test)"; exit;;
  esac
done

if [ "$TEST" == "1" ]; then
  N="-n";
else 
  N=""
fi

# first see if all hosts are up

for host in "${hosts[@]}"
do
  ssh -o StrictHostKeyChecking=no roundcube@$host "date"	
done

# now actually sync

for host in "${hosts[@]}"
do
  rsync $N -navH -O --delete --exclude=SQL --exclude=.deploy --exclude=.git --exclude=storing.inc --exclude=.gitignore --exclude=.gitmodules --exclude=bin ./ roundcube@$host:/data/WWW/release-1.0/
done